name: Update Year Progress

on:
  schedule:
    - cron: '0 14 * * *' # Run every day at midnight UTC

jobs:
  update_progress:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run script
        run: |
          python year_progress.py > progress.txt

      - name: Update README
        uses: Zilunl/git-auto-commit-action@v4
        with:
          commit_message: "Update Year Progress"
          file_pattern: progress.txt
