# update_year_progress.yml

name: Update Year Progress

on:
  schedule:
    - cron: '0 14 * * *' 

jobs:
  update_progress:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run script
        id: calculate_progress
        run: |
          output=$(python .github/workflows/year_progress.py)
          progress=$(echo $output | cut -d' ' -f1)
          progress_bar=$(echo $output | cut -d' ' -f2)
          current_date=$(echo $output | cut -d' ' -f3)
          echo "::set-output name=progress::$progress"
          echo "::set-output name=progress_bar::$progress_bar"
          echo "::set-output name=current_date::$current_date"

      - name: Update README
        run: |
          progress=$(echo "${{ steps.calculate_progress.outputs.progress }}")
          progress_bar=$(echo "${{ steps.calculate_progress.outputs.progress_bar }}")
          current_date=$(echo "${{ steps.calculate_progress.outputs.current_date }}")
          sed -i "s/{ █████.*/{ $progress_bar } $progress % as on ⏰ $current_date/" README.md
          git add README.md
          git commit -m "Update year progress"
          git push
