name: Update Year Progress

on:
  schedule:
    - cron: '0 14 * * *' # Run every day at 14:00 UTC, which is 00:00 AEST

jobs:
  update_progress:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run script
        id: calculate_progress
        run: |
          output=$(python .github/workflows/year_progress.py)
          echo "output=$output" >> $GITHUB_ENV

      - name: Update README
        run: |
          sed -i "s/⏳.*/output" README.md
          git add README.md
          git commit -m "Update year progress"
          git push
